background = "#f4f4f0"
background-alpha = 1.0
text = "#171716"
placeholder = "#5b5b57"
text-error = "#7a1f24"
border = "#171716"
border-active = "#171716"
border-error = "#7a1f24"
border-alpha = 1.0
border-width = 2
selection = "#d0d0cc"
selection-alpha = 1.0
