scrim = "#aaa9a4"
scrim-alpha = 1.0
text = "#171716"
selected-border = "#171716"
selected-border-alpha = 1.0
selected-border-width = 2
unselected-border = "#50504c"
unselected-border-alpha = 1.0
unselected-border-width = 1
