const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")

const overview = fs.readFileSync("../Overview.qml", "utf8")
const card = fs.readFileSync("../WindowCard.qml", "utf8")
const helper = fs.readFileSync("../move-window-to-workspace", "utf8")

test("overview exposes the shared Inspector boundary", () => {
  assert.match(overview, /signal inspectRequested\(var payload, string screenName\)/)
  assert.match(overview, /function performInspectorAction\(actionId, context\)/)
  assert.match(overview, /windowForIdentity\(root\.inspectorIdentity\(data\)\)/)
  assert.match(card, /controller\.requestInspector\(card\.modelData\)/)
})

test("workspace moving stays behind a validated argument-array dispatcher", () => {
  assert.match(overview, /WorkspaceModel\.moveRequest/)
  assert.match(overview, /workspaceMoveProcess\.command = \[/)
  assert.doesNotMatch(overview, /hyprctl dispatch movetoworkspace/)
  assert.match(helper, /\^0x\[0-9a-fA-F\]\{1,16\}\$/)
  assert.match(helper, /hyprctl -j clients/)
  assert.match(helper, /hyprctl -j workspaces/)
  assert.match(helper, /hyprctl -j monitors/)
  assert.match(helper, /\.initialClass \/\/ ""\) == \$initial_class/)
  assert.match(helper, /\.initialTitle \/\/ ""\) == \$initial_title/)
  assert.equal(fs.statSync("../move-window-to-workspace").mode & 0o111, 0)
  assert.match(overview, /"\/bin\/bash",\s*root\.pluginDir \+ "\/move-window-to-workspace"/)
  assert.match(helper, /hl\.dsp\.window\.move\(\{ workspace = \\"\$workspace_id\\", follow = false, window = \\"address:\$address\\" \}\)/)
  assert.match(helper, /hyprctl dispatch movetoworkspacesilent "\$workspace_id,address:\$address"/)
  assert.ok(helper.indexOf("hl.dsp.window.move") < helper.indexOf("movetoworkspacesilent"))
})

test("workspace UI keeps pointer and keyboard action parity", () => {
  assert.match(overview, /acceptedButtons: Qt\.LeftButton \| Qt\.RightButton/)
  assert.match(overview, /Qt\.Key_Menu/)
  assert.match(overview, /Qt\.Key_F10/)
  assert.match(overview, /moveWorkspaceCursor/)
  assert.match(overview, /moveSelectedWindowToWorkspace/)
  assert.match(overview, /Accessible\.name: "Workspace board for "/)
})

test("workspace board pins a monitor scope and explains unsupported workspaces", () => {
  assert.match(overview, /property string workspaceBoardMonitorName/)
  assert.match(overview, /chooseMonitorScope/)
  assert.match(overview, /reconcileWorkspaceBoardMonitor/)
  assert.match(overview, /DESKS \/ /)
  assert.match(overview, /Named, special, unassigned, and out-of-range workspaces are not actionable/)
  assert.match(overview, /unsupportedWorkspaceReason\(\)/)
  assert.match(overview, /return JSON\.stringify\(ids\);/)
})

test("workspace moves expose requested, confirmed, pending, and refused truth", () => {
  assert.match(overview, /Move requested:/)
  assert.match(overview, /Move confirmed:/)
  assert.match(overview, /Move pending:/)
  assert.match(overview, /Move refused:/)
  assert.match(overview, /WorkspaceModel\.parseMoveResult/)
  assert.match(overview, /windowForIdentity/)
  assert.match(helper, /printf 'confirmed\\t/)
  assert.match(helper, /printf 'pending\\t/)
  assert.match(helper, /exit 75/)
  assert.match(overview, /function getWorkspaceBoardMonitor\(\): string/)
  assert.match(overview, /function getWorkspaceMoveState\(\): string/)
  assert.match(overview, /function getWorkspaceNotice\(\): string/)
  assert.match(overview, /function getOrdinaryWorkspaceIds\(\): string/)
  assert.match(overview, /function getUnsupportedWorkspaceCount\(\): string/)
})
