normal-color = "#20242b"
normal-fill-alpha = 0.04
normal-border = "#20242b"
normal-border-width = 1
normal-border-alpha = 0.12
hover-cursor-color = "#1769d2"
hover-cursor-fill-alpha = 0.10
hover-cursor-border = "#1769d2"
hover-cursor-border-width = 1
hover-cursor-border-alpha = 0.34
focus-color = "#1769d2"
focus-fill-alpha = 0.12
focus-border = "#1769d2"
focus-border-width = 1
focus-border-alpha = 0.58
selected-color = "#1769d2"
selected-fill-alpha = 0.14
selected-border = "#1769d2"
selected-border-width = 0
selected-border-alpha = 0.0
pressed-fill-alpha = 0.20
selection-fill-alpha = 0.28
